import {defineStore} from 'pinia';
import state from "@quasar/app-vite/templates/app/ts/store/vuex/state";

export const Statstore = defineStore('stats', {
  state: () => ({
    character1: {
      id: 1,
      type: 0,
      name: "ZASALAMEL",
      race:"Automaton",
      class:"Thamaturge",
      level:1,
      stats: {
        str: 10,
        dex: 14,
        con: 12,
        int: 8,
        wis: 12,
        cha: 10,
      },
      modifiers: {
        str: +0,
        dex: +2,
        con: +1,
        int: -2,
        wis: +1,
        cha: +0,
      },
      skills: {
        acro: +2,
        arca: +0,
        athl: +4,
        craf: -2,
        dece: +6,
        dipl: +2,
        inti: +0,
        lore: +2,
        medi: +3,
        natu: +1,
        occu: +0,
        perf: +4,
        perc: +7,
        reli: +5,
        soci: +6,
        stel: +10,
        surv: +3,
        thie: +8,
      },
      defense: {
        ac: 15,
        hp: 12,
        fort: +1,
        refl: +4,
        will: +7,
      }
    },
    character2: {
      id: 2,
      type: 0,
      name: "WILT MBONDU",
      stats: {
        str: 13,
        dex: 11,
        con: 15,
        int: 10,
        wis: 16,
        cha: 8,
      },
      modifiers: {
        str: +1,
        dex: +0,
        con: +2,
        int: +0,
        wis: +3,
        cha: -2,
      },
      skills: {
        acro: +2,
        arca: +4,
        athl: +4,
        craf: +0,
        dece: +5,
        dipl: +3,
        inti: +3,
        lore: +2,
        medi: +4,
        natu: +2,
        occu: +3,
        perf: +5,
        reli: +6,
        soci: +5,
        stel: +1,
        surv: +3,
        thie: +2,
      },
      defense: {
        ac: 15,
        hp: 12,
        fort: +3,
        refl: +4,
        will: +3,
      }
    }
  }),
});
